In [4]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

print(tf.__version__)


2.7.0


In [15]:
datasetfilename = 'cvdataset.npz'

with np.load(datasetfilename, allow_pickle=True) as data:
    dataImages = data['images']
    dataLabel = data['labels']
    dataLabelNames = data['labelnames']
    
print(dataImages.shape)
print(dataLabel.shape)
#print(dataLabelNames.shape)

KeyError: 'labelnames is not a file in the archive'

In [4]:
dataImages.dtype, dataLabel.dtype, dataLabelNames.dtype

NameError: name 'dataLabelNames' is not defined

In [23]:
print(dataLabel)
print(dataLabelNames)

[0 1 2 3 4 5 6 7 8 1 2 4 6 7 8 1 2 3 4 5 6 7 0 1 4 5 6 7 8 0 1 4 5 6 7 8]
['afiq' 'azureen' 'gavin' 'goke' 'inamul' 'jincheng' 'mahmuda' 'numan'
 'saseendran' 'azureen' 'gavin' 'inamul' 'mahmuda' 'numan' 'saseendran'
 'azureen' 'gavin' 'goke' 'inamul' 'jincheng' 'mahmuda' 'numan' 'afiq'
 'azureen' 'inamul' 'jincheng' 'mahmuda' 'numan' 'saseendran' 'afiq'
 'azureen' 'inamul' 'jincheng' 'mahmuda' 'numan' 'saseendran']


In [24]:
classNames = sorted(np.unique(dataLabelNames))
print(classNames)

['afiq', 'azureen', 'gavin', 'goke', 'inamul', 'jincheng', 'mahmuda', 'numan', 'saseendran']


In [25]:
import cv2 as cv

N = len(dataImages)
shape = (N, 200,200,3)

y = np.empty(shape, dtype='uint8')

for i in range(N):
    y[i] = cv.resize(dataImages[i], [200,200], interpolation=cv.INTER_NEAREST)
    
dataImages.dtype, y.dtype, y.shape

dataImages = y

In [26]:
# Split the data to train and test
trainImages, testImages, trainLabels, testLabels = train_test_split(dataImages, dataLabel, test_size=0.3, random_state=42)

print(dataImages.shape)
print(dataLabel)

print(trainImages.shape)
print(testImages.shape)
print(testLabels)

(36, 200, 200, 3)
[0 1 2 3 4 5 6 7 8 1 2 4 6 7 8 1 2 3 4 5 6 7 0 1 4 5 6 7 8 0 1 4 5 6 7 8]
(25, 200, 200, 3)
(11, 200, 200, 3)
[8 7 6 1 2 4 7 6 8 3 1]


In [27]:
# classNames = sorted(np.unique(dataLabelNames))
# dataLabel[0]

In [28]:
# plt.figure()

# i = 0
# plt.imshow(trainImages[i])
# plt.title(f'{trainLabels[i]}')
# # plt.xlabel(classNames[dataLabel[i]])
# plt.show()

In [29]:
import numpy as np

print(trainImages[0].shape)
print(trainImages[1].shape)

(200, 200, 3)
(200, 200, 3)


In [30]:
for i in range(len(trainImages)):
    trainImages[i] = cv.resize(trainImages[i], [200,200], interpolation=cv.INTER_NEAREST)


In [31]:
inputShape = trainImages[0].shape
outputShape = len(classNames)

inputShape, outputShape

((200, 200, 3), 9)

In [32]:
trainImages = trainImages / 255
testImages = testImages / 255

In [33]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=inputShape),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(outputShape)
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 120000)            0         
                                                                 
 dense_4 (Dense)             (None, 128)               15360128  
                                                                 
 dense_5 (Dense)             (None, 128)               16512     
                                                                 
 dense_6 (Dense)             (None, 128)               16512     
                                                                 
 dense_7 (Dense)             (None, 9)                 1161      
                                                                 
Total params: 15,394,313
Trainable params: 15,394,313
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(optimizer='adam', loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [35]:
model.fit(trainImages, trainLabels, epochs=10)

Epoch 1/10
1/1 [==============================] - 1s 719ms/step - loss: 2.2233 - accuracy: 0.1200
Epoch 2/10
1/1 [==============================] - 0s 98ms/step - loss: 19.7813 - accuracy: 0.3200
Epoch 3/10
1/1 [==============================] - 0s 93ms/step - loss: 23.9921 - accuracy: 0.2800
Epoch 4/10
1/1 [==============================] - 0s 106ms/step - loss: 24.2535 - accuracy: 0.1200
Epoch 5/10
1/1 [==============================] - 0s 96ms/step - loss: 10.9007 - accuracy: 0.2000
Epoch 6/10
1/1 [==============================] - 0s 109ms/step - loss: 12.5286 - accuracy: 0.2800
Epoch 7/10
1/1 [==============================] - 0s 99ms/step - loss: 8.1498 - accuracy: 0.4000
Epoch 8/10
1/1 [==============================] - 0s 95ms/step - loss: 8.2249 - accuracy: 0.4000
Epoch 9/10
1/1 [==============================] - 0s 102ms/step - loss: 8.0867 - accuracy: 0.0800
Epoch 10/10
1/1 [==============================] - 0s 103ms/step - loss: 4.7092 - accuracy: 0.5600


In [36]:
testLoss, testAcc = model.evaluate(testImages, testLabels, verbose=2)

print('\nTest accuracy:', testAcc)

1/1 - 0s - loss: 5.5695 - accuracy: 0.3636 - 120ms/epoch - 120ms/step

Test accuracy: 0.3636363744735718


In [37]:
predictions = model.predict(testImages)
predictions[0]

array([ 1.1445051e+01,  9.9271364e+00, -2.3824333e+01,  3.9177230e-03,
       -1.3969663e+00,  1.2163013e+01,  7.5254040e+00,  8.8033066e+00,
        1.1619005e+01], dtype=float32)

In [38]:
i = 1
predictedLabel = np.argmax(predictions[i])
predictedLabel, testLabels[i], predictedLabel == testLabels[i]


(7, 7, True)